apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-condor
  labels:
    app: condor
spec:
  serviceName: "pandacore"
  replicas: 2
  selector:
    matchLabels:
      app: pandacore
  template:
    metadata:
      labels:
        app: pandacore
    spec:
      containers:
        - name: condor-container
          image: handson123/condor
          imagePullPolicy: Always
#          command: ["/usr/bin/supervisord","-c","/etc/supervisord.conf"]
          command: ["/usr/bin/bash","-c"]
          args:
            - export init_id=`cat /mnt/init/SCHEDD_CLUSTER_INITIAL_VALUE`;
              groupadd -g {{ .Values.GID }} {{ .Values.gname }};
              useradd -g {{ .Values.GID }} -u {{ .Values.UID }} {{ .Values.uname }};
              mkdir /etc/grid-security;
              ln -s /cvmfs/cms.cern.ch/grid/etc/grid-security/certificates /etc/grid-security/certificates;
              ln -s /mnt/condor/config.d/condor_config.local /etc/condor/config.d/condor_config.local;
              supervisord -c /etc/supervisord.conf
          volumeMounts:
            - name: condor-config
              mountPath: /mnt/condor/config.d
            - name: sharedfs
              mountPath: /sharedfs
            - name: cvmfs-cms
              mountPath: /cvmfs/cms.cern.ch
            - name: cvmfs-atlas
              mountPath: /cvmfs/atlas.cern.ch
            - name: init-dir
              mountPath: /mnt/init
      initContainers:
        - name: condor-init
          image: handson123/initcondor
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: DB_USER
              value: {{ .Values.database.user | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: DB_SCHEMA
              value: {{ .Values.database.schema | quote }}
          volumeMounts:
            - name: init-dir
              mountPath: "/mnt/init"
      volumes:
        - name: condor-config
          configMap:
            name: condor-config 
        - name: sharedfs
          hostPath:
            path: /var/sharedfs
            type: Directory
        - name: cvmfs-cms
          persistentVolumeClaim:
            claimName: csi-cvmfs-cms-pvc
            readOnly: true
        - name: cvmfs-atlas
          persistentVolumeClaim:
            claimName: csi-cvmfs-atlas-pvc
            readOnly: true
        - name: init-dir
          emptyDir: {}
      restartPolicy: Always
