apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-harvester-cron
  namespace: default
data:
{{ (.Files.Glob "harvester-cron/*").AsConfig | indent 2 }} 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-condor-cron
  namespace: default
data:
{{ (.Files.Glob "condor-cron/*").AsConfig | indent 2 }}
