apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.domain }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
spec:
  selector:
    app: {{ .Values.domain }}
  clusterIP: None

---
{{ if .Values.mariadb.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mariadb
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "2"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: pandacore
  template:
    metadata:
      labels:
        app: pandacore
    spec:
      hostname: mariadb
      subdomain: pandacore
      containers:
      - name: mariadb
        image: mariadb:latest
        imagePullPolicy: "Always"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mariadb.RootPassword }}
        - name: MYSQL_DATABASE
          value: {{ .Values.database.schema }}
        - name: MYSQL_USER
          value: {{ .Values.database.user }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.database.password }}
        ports:
        - containerPort: 3306
{{ end }}
