apiVersion: v1
data:
  panda_logroate: |
    /var/log/panda/*log {
        create 0644 {{ .Values.uname }} {{ .Values.gname }}
        rotate 180
        daily
        compress
        missingok
        notifempty
        su {{ .Values.uname }} {{ .Values.gname }}
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-logroate
