apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-harvester
  labels:
    app: harvester
spec:
  serviceName: {{ .Values.domain | quote }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.domain }}
  template:
    metadata:
      labels:
        app: {{ .Values.domain }}
    spec:
      containers:
        - name: harvester-container
          image: pandawms/harvester:centos7
          imagePullPolicy: Always
          securityContext:
              privileged: true
          resources:
              requests:
                cpu: 1
                memory: 2Gi
          command: ["/usr/bin/bash","-c"]
          args:
            - groupadd -g {{ .Values.GID }} {{ .Values.gname }};
              useradd -g {{ .Values.GID }} -u {{ .Values.UID }} {{ .Values.uname }};
              chown -R {{ .Values.uname }}:{{ .Values.gname }} /var/log/panda;
              echo {{ .Values.uname }} "ALL = (root) NOPASSWD:ALL" > /etc/sudoers.d/{{ .Values.uname }};
              cp /k8s-secrets/atlpan_k8s_sharedfs_id_ecdsa /home/{{ .Values.uname }}/;
              chmod 400 /home/{{ .Values.uname }}/atlpan_k8s_sharedfs_id_ecdsa;
              chown {{ .Values.uname }}:{{ .Values.gname }}  /home/{{ .Values.uname }}/atlpan_k8s_sharedfs_id_ecdsa;
              mkdir /sharedfs;
              sshfs -o allow_other -o StrictHostKeyChecking=no -o IdentityFile=/home/{{ .Values.uname }}/atlpan_k8s_sharedfs_id_ecdsa atlpan@aipanda028:/data2/atlpan/sharedvolume/ /sharedfs/;
              sh /usr/harvester_start.sh
          env:
          - name: RESTART_CYCLE
            value: '86400'
          - name: HARVESTER_UNAME
            value: {{ .Values.uname }}
          - name: HARVESTER_GNAME
            value: {{ .Values.gname }}
          volumeMounts:
          - name: panda-config
            mountPath: /usr/etc/panda
            readOnly: False
          - name: sysconfig-config
            mountPath: /usr/etc/sysconfig
            readOnly: True
          - name: cvmfs-cms
            mountPath: /cvmfs/cms.cern.ch
            readOnly: True
          - name: cvmfs-atlas
            mountPath: /cvmfs/atlas.cern.ch
            readOnly: True
          - name: sshkey
            mountPath: /k8s-secrets
      volumes:
        - name: panda-config
          projected:
            sources:
            - configMap:
                name: {{ .Release.Name }}-common
            - configMap:
                name: {{ .Release.Name }}-harvester-cfg
            - configMap:
                name: {{ .Release.Name }}-queueconfig
            - configMap:
                name: {{ .Release.Name }}-uwsgi
            - configMap:
                name: {{ .Release.Name }}-logroate
            - configMap:
                name: {{ .Release.Name }}-submitter-config
        - name: sysconfig-config
          configMap:
            name: {{ .Release.Name }}-sysconfig
        - name: cvmfs-cms
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-csi-cvmfs-cms-pvc
            readOnly: true
        - name: cvmfs-atlas
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-csi-cvmfs-atlas-pvc
            readOnly: true
        - name: sshkey
          secret:
            secretName: pre-sshkey
      restartPolicy: Always
{{- if .Values.DNSserver }}
      dnsConfig:
        nameservers:
          - {{ .Values.DNSserver }}
{{- end }}

